export type CatalogViewDto = "grid" | "list" | "map";
export type CatalogQueryDto = {
	q?: string;
	city?: string;
	district?: string;
	category?: string;
	dealType?: "sale" | "rent";
	rooms?: number | number[];
	studio?: boolean;
	exclusive?: boolean;
	priceFrom?: number;
	priceTo?: number;
	areaFrom?: number;
	areaTo?: number;
	kitchenFrom?: number;
	floorFrom?: number;
	floorTo?: number;
	lotAreaFrom?: number;
	lotAreaTo?: number;
	buildingType?: string;
	renovation?: string;
	landUseType?: string;
	hasElectricity?: boolean;
	hasGas?: boolean;
	hasWater?: boolean;
	hasSewerage?: boolean;
	commercialType?: string;
	commercialBuildingType?: string;
	entranceType?: string;
	sort?: "recommended" | "newest" | "price_asc" | "price_desc" | "area_desc";
	view?: CatalogViewDto;
	limit?: number;
	page?: number;
};
export type CatalogFacetOptionDto = {
	label: string;
	value: string;
	count?: number;
	parent?: string | null;
};
export type CatalogFacetsDto = {
	cities: CatalogFacetOptionDto[];
	districts: CatalogFacetOptionDto[];
	rooms: Array<{ value: number; count?: number }>;
	price: { min: number | null; max: number | null };
	buildingTypes: CatalogFacetOptionDto[];
	renovations: CatalogFacetOptionDto[];
	landUseTypes: CatalogFacetOptionDto[];
	commercialTypes: CatalogFacetOptionDto[];
	commercialBuildingTypes: CatalogFacetOptionDto[];
	entranceTypes: CatalogFacetOptionDto[];
};
