// Generated by pnpm seo:registry:generate. Do not edit manually.
import { assertSeoRegistry, type SeoRegistryRow } from "../../core/seo/registry.ts";
import { siteProfile } from "../site-profile.ts";
import { createProjectUrlGrammar, type ProjectDistrictRouteRegistry } from "../url-grammar.ts";
import type { ProjectSeoTemplateKey } from "./templates.ts";

export const projectDistrictRouteRegistry = {
  "rostov-na-donu": {
    "kvartiry": [
      "leninskiy",
      "voroshilovskiy",
      "severnyy",
      "tsentr"
    ]
  }
} as const satisfies ProjectDistrictRouteRegistry;
const grammar = createProjectUrlGrammar(siteProfile, projectDistrictRouteRegistry);

export const projectSeoRegistrySeed: readonly SeoRegistryRow<ProjectSeoTemplateKey>[] = [
  {
    "pageKey": {
      "kind": "home"
    },
    "url": "/",
    "canonical": "/",
    "entityRef": null,
    "targetPhrases": [
      "client skeleton /"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "homeSingleGeo",
    "title": "Недвижимость Ростова-на-Дону — Союз застройщиков",
    "h1": "Недвижимость Ростова-на-Дону",
    "description": "Подбор недвижимости в Ростове-на-Дону",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryRoot",
      "category": "kvartiry"
    },
    "url": "/kvartiry/",
    "canonical": "/kvartiry/",
    "entityRef": "category:kvartiry",
    "targetPhrases": [
      "client skeleton /kvartiry/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryRoot",
    "title": "Квартиры — Союз застройщиков",
    "h1": "Квартиры",
    "description": "Квартиры — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryRoot",
      "category": "novostroyki"
    },
    "url": "/novostroyki/",
    "canonical": "/novostroyki/",
    "entityRef": "category:novostroyki",
    "targetPhrases": [
      "client skeleton /novostroyki/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryRoot",
    "title": "Новостройки — Союз застройщиков",
    "h1": "Новостройки",
    "description": "Новостройки — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "geoHub",
      "geo": "rostov-na-donu"
    },
    "url": "/rostov-na-donu/",
    "canonical": "/rostov-na-donu/",
    "entityRef": "geo:rostov-na-donu",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "geoHub",
    "title": "Недвижимость Ростова-на-Дону — Союз застройщиков",
    "h1": "Недвижимость Ростова-на-Дону",
    "description": "квартиры и новостройки в Ростове-на-Дону",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeo",
      "geo": "rostov-na-donu",
      "category": "kvartiry"
    },
    "url": "/rostov-na-donu/kvartiry/",
    "canonical": "/rostov-na-donu/kvartiry/",
    "entityRef": "geo:rostov-na-donu/category:kvartiry",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/kvartiry/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeo",
    "title": "Квартиры в Ростове-на-Дону — Союз застройщиков",
    "h1": "Квартиры в Ростове-на-Дону",
    "description": "Квартиры в Ростове-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeoDistrict",
      "geo": "rostov-na-donu",
      "category": "kvartiry",
      "district": "leninskiy"
    },
    "url": "/rostov-na-donu/kvartiry/leninskiy/",
    "canonical": "/rostov-na-donu/kvartiry/leninskiy/",
    "entityRef": "geo:rostov-na-donu/category:kvartiry/district:leninskiy",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/kvartiry/leninskiy/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoDistrictAdmin",
    "title": "Купить квартиру в Ленинском районе Ростова-на-Дону — цены",
    "h1": "Квартиры в Ленинском районе Ростова-на-Дону",
    "description": "Квартиры в Ленинском районе Ростова-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeoDistrict",
      "geo": "rostov-na-donu",
      "category": "kvartiry",
      "district": "voroshilovskiy"
    },
    "url": "/rostov-na-donu/kvartiry/voroshilovskiy/",
    "canonical": "/rostov-na-donu/kvartiry/voroshilovskiy/",
    "entityRef": "geo:rostov-na-donu/category:kvartiry/district:voroshilovskiy",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/kvartiry/voroshilovskiy/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoDistrictAdmin",
    "title": "Купить квартиру в Ворошиловском районе Ростова-на-Дону — цены",
    "h1": "Квартиры в Ворошиловском районе Ростова-на-Дону",
    "description": "Квартиры в Ворошиловском районе Ростова-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeoDistrict",
      "geo": "rostov-na-donu",
      "category": "kvartiry",
      "district": "severnyy"
    },
    "url": "/rostov-na-donu/kvartiry/severnyy/",
    "canonical": "/rostov-na-donu/kvartiry/severnyy/",
    "entityRef": "geo:rostov-na-donu/category:kvartiry/district:severnyy",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/kvartiry/severnyy/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoDistrictMicro",
    "title": "Купить квартиру на Северном в Ростове-на-Дону — цены",
    "h1": "Квартиры на Северном",
    "description": "Квартиры на Северном в Ростове-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeoDistrict",
      "geo": "rostov-na-donu",
      "category": "kvartiry",
      "district": "tsentr"
    },
    "url": "/rostov-na-donu/kvartiry/tsentr/",
    "canonical": "/rostov-na-donu/kvartiry/tsentr/",
    "entityRef": "geo:rostov-na-donu/category:kvartiry/district:tsentr",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/kvartiry/tsentr/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoDistrictMicro",
    "title": "Купить квартиру в Центре в Ростове-на-Дону — цены",
    "h1": "Квартиры в Центре",
    "description": "Квартиры в Центре в Ростове-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeo",
      "geo": "rostov-na-donu",
      "category": "novostroyki"
    },
    "url": "/rostov-na-donu/novostroyki/",
    "canonical": "/rostov-na-donu/novostroyki/",
    "entityRef": "geo:rostov-na-donu/category:novostroyki",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/novostroyki/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeo",
    "title": "Новостройки в Ростове-на-Дону — Союз застройщиков",
    "h1": "Новостройки в Ростове-на-Дону",
    "description": "Новостройки в Ростове-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "geoDevelopers",
      "geo": "rostov-na-donu"
    },
    "url": "/rostov-na-donu/zastroyshchiki/",
    "canonical": "/rostov-na-donu/zastroyshchiki/",
    "entityRef": "geo:rostov-na-donu/developers",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/zastroyshchiki/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "geoDevelopers",
    "title": "Застройщики в Ростове-на-Дону — Союз застройщиков",
    "h1": "Застройщики в Ростове-на-Дону",
    "description": "Застройщики и жилые комплексы в Ростове-на-Дону",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "developerGeo"
  },
  {
    "pageKey": {
      "kind": "developerRoot"
    },
    "url": "/zastroyshchiki/",
    "canonical": "/zastroyshchiki/",
    "entityRef": "developers:root",
    "targetPhrases": [
      "client skeleton /zastroyshchiki/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "developerRoot",
    "title": "Застройщики — Союз застройщиков",
    "h1": "Застройщики",
    "description": "Застройщики и жилые комплексы",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "developerGeo"
  },
  {
    "pageKey": {
      "kind": "categoryGeoFacet",
      "geo": "rostov-na-donu",
      "category": "kvartiry",
      "facet": "vtorichka"
    },
    "url": "/rostov-na-donu/kvartiry/vtorichka/",
    "canonical": "/rostov-na-donu/kvartiry/vtorichka/",
    "entityRef": "facet:vtorichka",
    "targetPhrases": [
      "client skeleton /rostov-na-donu/kvartiry/vtorichka/"
    ],
    "metric": "broad39",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-10-01",
    "synthetic": false,
    "tier": "NONE",
    "minimumObjects": 0,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoFacet",
    "title": "Вторичные квартиры в Ростове-на-Дону — Союз застройщиков",
    "h1": "Вторичные квартиры в Ростове-на-Дону",
    "description": "Вторичные квартиры в Ростове-на-Дону — актуальные предложения",
    "status": "draft",
    "morphologyApproved": true,
    "release": "client-bootstrap",
    "contentGateRule": "listing"
  }
] as const;

assertSeoRegistry({ rows: projectSeoRegistrySeed, buildUrl: grammar.buildUrl, now: new Date("2026-10-01T23:59:59.999Z") });
