/* Generated by clone:prepare from the approved clone preset. */
import { Manrope } from "next/font/google";

export const projectFont = Manrope({
	display: "swap",
	subsets: ["cyrillic", "latin"],
	variable: "--font-project",
});
